"""
D365 Demo Copilot — Interactive Setup Wizard

Guides the user through configuring all required credentials and
writes (or updates) the .env file.  Also validates Dataverse OAuth
by attempting to acquire a token.

Usage:
    python -m demo_agent --setup
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.table import Table

console = Console()

ENV_PATH = Path(__file__).parent.parent / ".env"

# Keys we manage, in display order
SECTIONS = [
    {
        "header": "LLM Provider (GitHub Models)",
        "keys": [
            ("GITHUB_TOKEN", "GitHub personal-access token", "", True),
            ("GITHUB_MODELS_BASE_URL", "GitHub Models endpoint", "https://models.github.ai/inference", False),
            ("GITHUB_COPILOT_MODEL", "Model name", "openai/gpt-5", False),
        ],
    },
    {
        "header": "D365 Environment",
        "keys": [
            ("D365_BASE_URL", "Dataverse org URL (e.g. https://myorg.crm.dynamics.com)", "https://projectopscoreagentimplemented.crm.dynamics.com", True),
        ],
    },
    {
        "header": "Dataverse OAuth — App Registration",
        "keys": [
            ("DATAVERSE_TENANT_ID", "Azure AD Tenant ID (GUID)", "", True),
            ("DATAVERSE_CLIENT_ID", "App Registration Client ID (GUID)", "", True),
            ("DATAVERSE_CLIENT_SECRET", "App Registration Client Secret", "", True),
        ],
    },
    {
        "header": "Browser",
        "keys": [
            ("BROWSER_HEADLESS", "Run browser headless?", "false", False),
            ("BROWSER_SLOW_MO", "Slow-mo delay (ms) for visibility", "50", False),
        ],
    },
]


def _read_env() -> dict[str, str]:
    """Parse existing .env into a dict (ignores comments)."""
    values: dict[str, str] = {}
    if not ENV_PATH.exists():
        return values
    for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^([A-Z_]+)\s*=\s*(.*)", line)
        if m:
            values[m.group(1)] = m.group(2)
    return values


def _write_env(values: dict[str, str]) -> None:
    """Write a clean .env file preserving section structure."""
    lines = [
        "# D365 Demo Copilot — Environment Configuration",
        "# Generated by: python -m demo_agent --setup",
        "",
    ]
    for section in SECTIONS:
        lines.append(f"# {section['header']}")
        for key, _desc, _default, _req in section["keys"]:
            val = values.get(key, "")
            lines.append(f"{key}={val}")
        lines.append("")
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _mask(value: str) -> str:
    """Mask a secret for display, showing first 4 and last 4 chars."""
    if len(value) <= 10:
        return "****"
    return value[:4] + "…" + value[-4:]


def run_setup() -> None:
    """Interactive setup wizard."""
    console.print()
    console.print(
        Panel.fit(
            "[bold blue]D365 Demo Copilot — Setup Wizard[/bold blue]\n\n"
            "[dim]This wizard will walk you through the required configuration.\n"
            "Press Enter to keep the current/default value shown in brackets.\n"
            "Secrets are masked in the display but stored in plain text in .env.[/dim]",
            border_style="blue",
            padding=(1, 3),
        )
    )

    existing = _read_env()
    updated: dict[str, str] = dict(existing)

    for section in SECTIONS:
        console.print(f"\n[bold cyan]── {section['header']} ──[/bold cyan]")

        for key, description, default, is_required in section["keys"]:
            current = existing.get(key, "")
            effective_default = current or default

            # Build display hint
            if current:
                is_secret = "SECRET" in key or "TOKEN" in key or "KEY" in key
                hint = _mask(current) if is_secret else current
            elif default:
                hint = default
            else:
                hint = ""

            prompt_text = f"  {description}"
            if hint:
                prompt_text += f" [dim]\\[{hint}][/dim]"

            is_secret = "SECRET" in key or "TOKEN" in key or "KEY" in key

            value = Prompt.ask(prompt_text, default=effective_default, password=is_secret)

            if is_required and not value:
                console.print(f"  [yellow]⚠ {key} is recommended but left empty[/yellow]")

            updated[key] = value

    # ---- Show summary ----
    console.print("\n")
    table = Table(title="Configuration Summary", show_lines=True)
    table.add_column("Setting", style="cyan")
    table.add_column("Value")

    for section in SECTIONS:
        for key, desc, _default, _req in section["keys"]:
            val = updated.get(key, "")
            is_secret = "SECRET" in key or "TOKEN" in key or "KEY" in key
            display = _mask(val) if (is_secret and val) else (val or "[dim]<empty>[/dim]")
            table.add_row(key, display)

    console.print(table)

    # ---- Validate Dataverse OAuth ----
    tenant = updated.get("DATAVERSE_TENANT_ID", "")
    client_id = updated.get("DATAVERSE_CLIENT_ID", "")
    client_secret = updated.get("DATAVERSE_CLIENT_SECRET", "")
    d365_url = updated.get("D365_BASE_URL", "")

    if tenant and client_id and client_secret and d365_url:
        console.print("\n[bold]Validating Dataverse OAuth credentials...[/bold]")
        try:
            from .auth.dataverse_auth import DataverseAuth

            auth = DataverseAuth(
                tenant_id=tenant,
                client_id=client_id,
                client_secret=client_secret,
                resource_url=d365_url,
            )
            token = auth.get_token()
            console.print(
                f"[green]✓ Token acquired successfully "
                f"({len(token)} chars, expires in ~1 hour)[/green]"
            )
        except Exception as exc:
            console.print(f"[red]✗ Token acquisition failed: {exc}[/red]")
            console.print(
                "[yellow]  The credentials will still be saved — "
                "you can fix them later by re-running --setup.[/yellow]"
            )
    else:
        console.print(
            "\n[yellow]Dataverse OAuth credentials incomplete — "
            "skipping token validation.[/yellow]"
        )

    # ---- Save ----
    if Confirm.ask("\nSave configuration?", default=True):
        _write_env(updated)
        console.print(f"[green]✓ Configuration saved to {ENV_PATH}[/green]")
    else:
        console.print("[dim]Cancelled — no changes written.[/dim]")

    console.print()
